### ISSUE TITLE
get_user_activities() errors out

### ISSUE THREAD

**Issue by stin7** [numerai/numerapi#22]
The following code used to work:
```
>>> import numerapi
>>> napi = numerapi.NumerAPI(verbosity="info")
>>> data = napi.get_user_activities("madmin")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/numerapi/numerapi.py", line 716, in get_user_activities
    if item['stake']['date'] is None:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by uuazed** [comment]
This error was fixed in numerapi version 2.1.3, please update via
`pip install --upgrade numerapi`
